messages:
  create-community: "&aYou created a new community!"
  delete-community: "&cYou removed your community!"
  warp: "&aYou teleported to %placeholder%!"
  warp-error: "&cA warp named %placeholder% could not be found!"
  no-invite: "&cYou do not have a pending invite from %placeholder%."
  invite-send: "&dYou invited %placeholder% to your community!"
  invite-receive: "&dYou received an invite from %placeholder%! Enter /pc accept %placeholder% to accept."
  invite-accepted: "&aYou accepted an invite from %placeholder%!"
  set-warp: "&aYou set a warp: %placeholder%!"
  must-be-owner: "&cYou must be the owner of a community to do this!"
  community-not-found: "&c%placeholder% not found!"
  player-not-found: "&cThe player %placeholder% was not found!"
  player-already-in-community: "&cThe player %placeholder% is already in your community!"
  player-joined-community: "&a%placeholder% joined your community!"
  set-description: "&aCommunity description set to: &6%placeholder%"
  generic-error: "&cAn error occurred!"
  community-list-header: "&6&lCommunities"
  community-list-line: "#&e%number% Name: %communityName% Members: %members%"
  community-already-exists: "&cA community with that name already exists!"
  already-in-community: "&cYou are already in a community!"
  self-invite-error: "&cYou can't invite yourself!"
  leave-community-owner: "&cYou can't leave your own community! Use /pc delete if you wish to remove it."
  not-in-community: "&cYou are not in a community!"
  leave-community: "&aYou left %placeholder%."
  syntax:
    create: "&cUsage: /%placeholder% create <name>"
    delete: "&cUsage: /%placeholder% delete"
    warp: "&cUsage: /%placeholder% warp <warpName>"
    setwarp: "&Usage: /%placeholder% setwarp <warpName>"
    invite: "&cUsage: /%placeholder% invite <player>"
    list: "&cUsage: /%placeholder% list"
    setdesc: "&Usage: /%placeholder% setdesc <description>"
    leave: "&Usage: /%placeholder% leave"
    accept: "&cUsage: /%placeholder% accept"

help:
  header: "&6&lPlayer Communities Help"
  line-1: "&e/%placeholder% create <name> - Create a new community"
  line-2: "&e/%placeholder% delete - Delete your community"
  line-3: "&e/%placeholder% warp <warpName> - Go to a warp"
  line-4: "&e/%placeholder% setwarp <name> - Set a warp"
  line-5: "&e/%placeholder% invite <player> - Invite a player"
  line-6: "&e/%placeholder% accept <community> - Accept an invite"
  line-7: "&e/%placeholder% leave - Leave your community"
  line-8: "&e/%placeholder% list - List the top communities"
