settings:
  guild-cost: 50000
messages:
  create-guild: "&aYou created a new guild!"
  disband-guild: "&cYou disbanded your guild!"
  warp: "&aYou teleported to %placeholder%!"
  warp-error: "&cA warp named %placeholder% could not be found!"
  no-invite: "&cYou do not have a pending invite from %placeholder%."
  invite-send: "&dYou invited %placeholder% to your guild!"
  invite-receive: "&dYou received an invite from %placeholder%! Enter /pc accept %placeholder% to accept."
  invite-accepted: "&aYou accepted an invite from %placeholder%!"
  invite-denied: "&cYou denied the invite from %placeholder%."
  set-warp: "&aYou set a warp: %placeholder%!"
  must-be-owner: "&cYou must be the owner of a guild to do this!"
  guild-not-found: "&c%placeholder% not found!"
  player-not-found: "&cThe player %placeholder% was not found!"
  player-already-in-guild: "&cThe player %placeholder% is already in your guild!"
  player-joined-guild: "&a%placeholder% joined your guild!"
  set-description: "&aGuild description set to: &6%placeholder%"
  generic-error: "&cAn error occurred!"
  guild-list-header: "&6&lGuilds"
  guild-list-line: "#&e%number% Name: %guildName% Members: %members%"
  guild-already-exists: "&cA Guild with that name already exists!"
  already-in-guild: "&cYou are already in a guild!"
  self-invite-error: "&cYou can't invite yourself!"
  leave-guild-owner: "&cYou can't leave your own guild! Use /pc delete if you wish to remove it."
  not-in-guild: "&cYou are not in a guild!"
  leave-guild: "&aYou left %placeholder%."
  not-console-command: "Only in-game players can do this command!"
  guild-set-name: "&aGuild name updated: %placeholder%"
  no-guilds: "&cNo guilds have been made yet!"
  no-special-characters: "&cSpecial characters are not allowed in this command!"
  guild-create-insufficient-funds: "&cYou need $%placeholder% to create a Guild."
  syntax:
    create: "&cUsage: /%placeholder% create <name>"
    disband: "&cUsage: /%placeholder% disband"
    warp: "&cUsage: /%placeholder% warp <warpName>"
    setwarp: "&Usage: /%placeholder% setwarp <warpName>"
    invite: "&cUsage: /%placeholder% invite <player>"
    deny-invite: "&cUsage: /%placeholder% deny <guild>"
    accept-invite: "&cUsage: /%placeholder% accept <guild>"
    list: "&cUsage: /%placeholder% list"
    setdesc: "&Usage: /%placeholder% setdesc <description>"
    leave: "&Usage: /%placeholder% leave"
    setname: "&cUsage: /%placeholder% setname <name>"

help:
  header: "&6&lGuilds Help"
  line-1: "&e/%placeholder% create <name> - Create a new guild"
  line-2: "&e/%placeholder% delete - Delete your guild"
  line-3: "&e/%placeholder% warp <warpName> - Go to a warp"
  line-4: "&e/%placeholder% setwarp <name> - Set a warp"
  line-5: "&e/%placeholder% invite <player> - Invite a player"
  line-6: "&e/%placeholder% accept <guild> - Accept an invite"
  line-7: "&e/%placeholder% leave - Leave your guild"
  line-8: "&e/%placeholder% list - List the top guilds"
