name: Guilds
version: '${project.version}'
main: com.justinmtech.guilds.Guilds
api-version: 1.17
authors: [ justinmtech ]
description: A plugin that allows players to create their own goal-oriented communities to inspire cooperation and socializing.
website: https://justinmtech.com
commands:
  guilds:
    description: Base command of Guilds.
    usage: "/guilds"
    aliases:
      - guild
      - guilds
      - g
  gc:
    description: Use guild chat.
    usage: "/gc <message>"
    aliases:
      - gc
      - gchat
      - guildchat
depend:
  - Vault
softdepend:
  - PlaceholderAPI

