name: Guilds
version: '${project.version}'
main: com.justinmtech.guilds.Guilds
api-version: 1.17
authors: [ justinmtech ]
description: A plugin that allows players to create their own goal-oriented communities to inspire cooperation and socializing.
website: https://justinm.tech
commands:
  guilds:
    description: Base command of Guilds.
    usage: ""
    aliases:
      - guild
      - guilds
      - g
depend:
  - Vault

