name: PlayerCommunities
version: '${project.version}'
main: tech.justinm.playercommunities.PlayerCommunities
api-version: 1.17
authors: [ justinmtech ]
description: A plugin that allows players to create their own goal-oriented communities to inspire cooperation and socializing.
website: https://justinm.tech
commands:
  playercommunities:
    description: Base command of Player Communities.
    usage: ""
    aliases:
      - pc
      - pcom
      - pcoms

